
(defun inspiration-630889 ()
  "Theme generated by http://inspiration.sweyla.com/code/"
  (interactive)
  (color-theme-install
   '(inspiration-630889
     ((background-color . "#000D00")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#FFF34F"))))
     (font-lock-constant-face ((t (:foreground "#FF7942"))))
     (font-lock-builtin-face ((t (:foreground "#8DB22D"))))
     (font-lock-function-name-face ((t (:foreground "#6EFE2A"))))
     (font-lock-variable-name-face ((t (:foreground "#FFFF00"))))
     (font-lock-keyword-face ((t (:foreground "#FFFF73"))))
     (font-lock-string-face ((t (:foreground "#F78700"))))
     (font-lock-doc-string-face ((t (:foreground "#F78700"))))
     (font-lock-type-face ((t (:foreground "#F71B27"))))
     )))

(provide 'inspiration-630889)