
(defun inspiration-976777 ()
  "Theme generated by http://inspiration.sweyla.com/code/"
  (interactive)
  (color-theme-install
   '(inspiration-976777
     ((background-color . "#0E0100")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#81FFA3"))))
     (font-lock-constant-face ((t (:foreground "#D06E43"))))
     (font-lock-builtin-face ((t (:foreground "#C4A462"))))
     (font-lock-function-name-face ((t (:foreground "#D76F4E"))))
     (font-lock-variable-name-face ((t (:foreground "#F0CA28"))))
     (font-lock-keyword-face ((t (:foreground "#6CFF3B"))))
     (font-lock-string-face ((t (:foreground "#F9A300"))))
     (font-lock-doc-string-face ((t (:foreground "#F9A300"))))
     (font-lock-type-face ((t (:foreground "#D76F4E"))))
     )))

(provide 'inspiration-976777)