
(defun inspiration-733956 ()
  "Theme generated by http://inspiration.sweyla.com/code/"
  (interactive)
  (color-theme-install
   '(inspiration-733956
     ((background-color . "#08000B")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#CBC46F" :foreground "#08000B"))))

     (font-lock-comment-face ((t (:foreground "#4E4E4E"))))
     (font-lock-constant-face ((t (:foreground "#87FF00"))))
     (font-lock-builtin-face ((t (:foreground "#D76F4E"))))
     (font-lock-function-name-face ((t (:foreground "#FFA315"))))
     (font-lock-variable-name-face ((t (:foreground "#D76F4E"))))
     (font-lock-keyword-face ((t (:foreground "#D76F4E"))))
     (font-lock-string-face ((t (:foreground "#759C62"))))
     (font-lock-doc-string-face ((t (:foreground "#509C97"))))
     (font-lock-type-face ((t (:foreground "#6081DE"))))
     )))

(provide 'inspiration-733956)