
(defun inspiration-715644 ()
  "Theme generated by http://inspiration.sweyla.com/code/"
  (interactive)
  (color-theme-install
   '(inspiration-715644
     ((background-color . "#0D1200")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#04C3A0"))))
     (font-lock-constant-face ((t (:foreground "#9FFF1F"))))
     (font-lock-builtin-face ((t (:foreground "#FFFF8F"))))
     (font-lock-function-name-face ((t (:foreground "#58B81C"))))
     (font-lock-variable-name-face ((t (:foreground "#97B189"))))
     (font-lock-keyword-face ((t (:foreground "#B8D7EB"))))
     (font-lock-string-face ((t (:foreground "#A2A68A"))))
     (font-lock-doc-string-face ((t (:foreground "#A2A68A"))))
     (font-lock-type-face ((t (:foreground "#FFFF7D"))))
     )))

(provide 'inspiration-715644)